#!/bin/bash

: '
    uscreen: simplified wrapper for screen command

        Author    : Viki - Vignesh Natarajan
        Contact   : vikiworks.io
'

if [ -z "$1" ]; then
    echo
    echo "      Usage: uscreen <new_screen_name>"
    echo
    echo
    echo "      Example: uscreen mytest_screen"
    echo
    echo
    echo "Note: "
    echo
    echo "This command does the following"
    echo 
    echo "      1. Attach to a screen if it exist"
    echo "      2. Create a screen if it doesn't exist"
    echo
    exit 1
fi

SCREEN_NAME="$1"

#echo "Trying to attach to screen by name ( $SCREEN_NAME )"
screen -d -r $SCREEN_NAME

if [ $? -ne 0 ]; then
    #echo "info: no screen by name ( $SCREEN_NAME ) exist"
    #echo "creating new screen by name ( $SCREEN_NAME )"
    screen -S $SCREEN_NAME
fi


